{{- $unmanagedSubscriptionExists := include "unmanaged-resource-exists" (list "operators.coreos.com/v1alpha1" "Subscription" .Values.openshiftPipelines.subscription.namespace .Values.openshiftPipelines.subscription.spec.name .Release.Name .Capabilities.APIVersions ) }}
{{- if and (eq $unmanagedSubscriptionExists "false") .Values.openshiftPipelines.enabled }}

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.openshiftPipelines.subscription.name }}
  namespace: {{ .Values.openshiftPipelines.subscription.namespace }}
spec:
  channel: {{ .Values.openshiftPipelines.subscription.spec.channel }}
  installPlanApproval: {{ .Values.openshiftPipelines.subscription.spec.installPlanApproval }}
  name: {{ .Values.openshiftPipelines.subscription.spec.name }}
  source: {{ .Values.openshiftPipelines.subscription.spec.source | default "redhat-operators"  }}
  sourceNamespace: {{ .Values.openshiftPipelines.subscription.spec.sourceNamespace | default "openshift-marketplace" }}
{{- end }}
